# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import document_processor_pb2 as document__processor__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in document_processor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class DocumentProcessorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessDocument = channel.unary_unary(
                '/documentprocessor.DocumentProcessor/ProcessDocument',
                request_serializer=document__processor__pb2.ProcessDocumentRequest.SerializeToString,
                response_deserializer=document__processor__pb2.ProcessDocumentResponse.FromString,
                _registered_method=True)
        self.ModifyDocument = channel.unary_unary(
                '/documentprocessor.DocumentProcessor/ModifyDocument',
                request_serializer=document__processor__pb2.ModifyDocumentRequest.SerializeToString,
                response_deserializer=document__processor__pb2.ModifyDocumentResponse.FromString,
                _registered_method=True)


class DocumentProcessorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessDocument,
                    request_deserializer=document__processor__pb2.ProcessDocumentRequest.FromString,
                    response_serializer=document__processor__pb2.ProcessDocumentResponse.SerializeToString,
            ),
            'ModifyDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyDocument,
                    request_deserializer=document__processor__pb2.ModifyDocumentRequest.FromString,
                    response_serializer=document__processor__pb2.ModifyDocumentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'documentprocessor.DocumentProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('documentprocessor.DocumentProcessor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentProcessor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/documentprocessor.DocumentProcessor/ProcessDocument',
            document__processor__pb2.ProcessDocumentRequest.SerializeToString,
            document__processor__pb2.ProcessDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModifyDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/documentprocessor.DocumentProcessor/ModifyDocument',
            document__processor__pb2.ModifyDocumentRequest.SerializeToString,
            document__processor__pb2.ModifyDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
