# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: document_processor.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'document_processor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64ocument_processor.proto\x12\x12\x64ocument_processor\"<\n\x16ProcessDocumentRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x11\n\tfile_type\x18\x02 \x01(\t\"+\n\x17ProcessDocumentResponse\x12\x10\n\x08segments\x18\x01 \x01(\t\"Q\n\x15ModifyDocumentRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x14\n\x0creplacements\x18\x02 \x01(\t\x12\x11\n\tfile_type\x18\x03 \x01(\t\"2\n\x16ModifyDocumentResponse\x12\x18\n\x10modified_content\x18\x01 \x01(\t2\xe8\x01\n\x11\x44ocumentProcessor\x12j\n\x0fProcessDocument\x12*.document_processor.ProcessDocumentRequest\x1a+.document_processor.ProcessDocumentResponse\x12g\n\x0eModifyDocument\x12).document_processor.ModifyDocumentRequest\x1a*.document_processor.ModifyDocumentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'document_processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSDOCUMENTREQUEST']._serialized_start=48
  _globals['_PROCESSDOCUMENTREQUEST']._serialized_end=108
  _globals['_PROCESSDOCUMENTRESPONSE']._serialized_start=110
  _globals['_PROCESSDOCUMENTRESPONSE']._serialized_end=153
  _globals['_MODIFYDOCUMENTREQUEST']._serialized_start=155
  _globals['_MODIFYDOCUMENTREQUEST']._serialized_end=236
  _globals['_MODIFYDOCUMENTRESPONSE']._serialized_start=238
  _globals['_MODIFYDOCUMENTRESPONSE']._serialized_end=288
  _globals['_DOCUMENTPROCESSOR']._serialized_start=291
  _globals['_DOCUMENTPROCESSOR']._serialized_end=523
# @@protoc_insertion_point(module_scope)
