# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: document_processor.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64ocument_processor.proto\x12\x11\x64ocumentprocessor\"T\n\x16ProcessDocumentRequest\x12\x12\n\ninput_path\x18\x01 \x01(\t\x12\x13\n\x0boutput_path\x18\x02 \x01(\t\x12\x11\n\tfile_type\x18\x03 \x01(\t\"+\n\x17ProcessDocumentResponse\x12\x10\n\x08segments\x18\x01 \x01(\t\"i\n\x15ModifyDocumentRequest\x12\x12\n\ninput_path\x18\x01 \x01(\t\x12\x13\n\x0boutput_path\x18\x02 \x01(\t\x12\x14\n\x0creplacements\x18\x03 \x01(\t\x12\x11\n\tfile_type\x18\x04 \x01(\t\")\n\x16ModifyDocumentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xe4\x01\n\x11\x44ocumentProcessor\x12h\n\x0fProcessDocument\x12).documentprocessor.ProcessDocumentRequest\x1a*.documentprocessor.ProcessDocumentResponse\x12\x65\n\x0eModifyDocument\x12(.documentprocessor.ModifyDocumentRequest\x1a).documentprocessor.ModifyDocumentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'document_processor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSDOCUMENTREQUEST']._serialized_start=47
  _globals['_PROCESSDOCUMENTREQUEST']._serialized_end=131
  _globals['_PROCESSDOCUMENTRESPONSE']._serialized_start=133
  _globals['_PROCESSDOCUMENTRESPONSE']._serialized_end=176
  _globals['_MODIFYDOCUMENTREQUEST']._serialized_start=178
  _globals['_MODIFYDOCUMENTREQUEST']._serialized_end=283
  _globals['_MODIFYDOCUMENTRESPONSE']._serialized_start=285
  _globals['_MODIFYDOCUMENTRESPONSE']._serialized_end=326
  _globals['_DOCUMENTPROCESSOR']._serialized_start=329
  _globals['_DOCUMENTPROCESSOR']._serialized_end=557
# @@protoc_insertion_point(module_scope)
